### ISSUE TITLE
add a meta struct (or two)

### ISSUE THREAD

**Issue by tzapu** [corpetty/go-alethio-api#10]
there are only two types of meta objects currently (with and without pagination) so it would make sense to have them as separate structs and embed them into the top level structs 
```
Meta:
  type: object
  description:
    en: Meta information about the request.
    zh: (...)
  properties:
    latestBlock:
      type: object
      description:
        en: Information about the latest block in the canonical chain.
        zh: (...)
      properties:
        number:
          description:
            en: The block number of the latest block.
            zh: (...)
          example: 7909779
          type: integer
​
        blockCreationTime:
          description:
            en: The inception timestamp (UTC) of the latest block.
            zh: (...)
          example: 1559879572
          format: unixtime
          type: integer
​
        blockHash:
          description:
            en: The hash of the latest block.
            zh: (...)
          example: '0x8f25ead8680577256d43d5401beeb9cefa4cc121478c79c75a2e23a4695aa450'
          format: hex256
          type: string
​
​
MetaPagination:
  type: object
  description: Meta information about the request.
  properties:
    latestBlock:
      type: object
      description: Information about the latest block in the canonical chain.
      properties:
        number:
          description:
            en: The block number of the latest block.
            zh: (...)
          example: 7909779
          type: integer
​
        blockCreationTime:
          description:
            en: The inception timestamp (UTC) of the latest block.
            zh: (...)
          example: 1559879572
          format: unixtime
          type: integer
​
        blockHash:
          description:
            en: The hash of the latest block.
            zh: (...)
          example: '0x8f25ead8680577256d43d5401beeb9cefa4cc121478c79c75a2e23a4695aa450'
          format: hex256
          type: string
​
    count:
      type: integer
      description:
        en: The number of items included in the current page.
        zh: (...)
      example: 10
​
    page:
      type: object
      description:
        en: Pagination flags.
        zh: (...)
      properties:
        hasNext:
          description:
            en: Flags `true` if the `next` page has at least one entry, `false` otherwise
            zh: (...)
          example: true
          type: boolean
​
        hasPrev:
          description:
            en: Flags `true` if the `prev` page has at least one entry, `false` otherwise
            zh: (...)
          example: true
          type: boolean
```
